# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: image_gen.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'image_gen.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0fimage_gen.proto\x12\x08imagegen\"\x1e\n\x0cImageRequest\x12\x0e\n\x06prompt\x18\x01 \x01(\t\"D\n\rImageResponse\x12\x0e\n\x06status\x18\x01 \x01(\t\x12\x12\n\nimage_path\x18\x02 \x01(\t\x12\x0f\n\x07message\x18\x03 \x01(\t2S\n\x0fImageGenService\x12@\n\rGenerateImage\x12\x16.imagegen.ImageRequest\x1a\x17.imagegen.ImageResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'image_gen_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_IMAGEREQUEST']._serialized_start=29
  _globals['_IMAGEREQUEST']._serialized_end=59
  _globals['_IMAGERESPONSE']._serialized_start=61
  _globals['_IMAGERESPONSE']._serialized_end=129
  _globals['_IMAGEGENSERVICE']._serialized_start=131
  _globals['_IMAGEGENSERVICE']._serialized_end=214
# @@protoc_insertion_point(module_scope)
