# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: pipeline.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'pipeline.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0epipeline.proto\x12\x08pipeline\"5\n\x0fPipelineRequest\x12\x0e\n\x06prompt\x18\x01 \x01(\t\x12\x12\n\nface_image\x18\x02 \x01(\x0c\"_\n\rPipelineReply\x12\x14\n\x0cresult_image\x18\x01 \x01(\x0c\x12\x0b\n\x03log\x18\x02 \x01(\t\x12\x13\n\x0bstatus_code\x18\x03 \x01(\x05\x12\x16\n\x0estatus_message\x18\x04 \x01(\t2R\n\rImagePipeline\x12\x41\n\x0bRunPipeline\x12\x19.pipeline.PipelineRequest\x1a\x17.pipeline.PipelineReplyb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'pipeline_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_PIPELINEREQUEST']._serialized_start=28
  _globals['_PIPELINEREQUEST']._serialized_end=81
  _globals['_PIPELINEREPLY']._serialized_start=83
  _globals['_PIPELINEREPLY']._serialized_end=178
  _globals['_IMAGEPIPELINE']._serialized_start=180
  _globals['_IMAGEPIPELINE']._serialized_end=262
# @@protoc_insertion_point(module_scope)
